version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: flask run -h 0.0.0.0
    volumes:
      - .:/usr/src/app/web/
    ports:
      - 5000:5000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coreanalysis
volumes:
  postgres_data:
