version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 "backend.main:create_app()"
    # volumes:
    #   - ./web/:/usr/src/app/web/
    ports:
      - 5000:5000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=coreanalysis
volumes:
  postgres_data:
